name: photo_buddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  adaptive_platform_ui: ^0.1.100
  cupertino_icons: ^1.0.8
  fc_native_video_thumbnail: ^0.17.2
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  image: ^4.7.2
  image_size_getter: ^2.4.1
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  macos_ui: ^2.2.2
  open_file_macos: ^0.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  pull_down_button: ^0.10.2
  shared_preferences: ^2.5.4
  tflite_flutter: ^0.12.1
  watcher: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.0
  build_runner:

flutter:
  uses-material-design: true
  assets: 
    - assets/icon/
    - assets/models/facenet.tflite
